version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/spf13/tfenvgo/cmd.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

brews:
  - name: tfenvgo
    repository:
      owner: dmakeienko
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/dmakeienko/tfenvgo"
    description: "Terraform version manager written in Go"
    license: "MIT"
    install: |
      bin.install "tfenvgo"
    test: |
      system "#{bin}/tfenvgo", "--version"

changelog:
  disable: true
