# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Publish Version
on:
  push:
    branches:
      - main

jobs:
  publish_tag:
    name: Publish Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: |
          npm install semantic-release \
              @semantic-release/github \
              @semantic-release/changelog \
              @semantic-release/commit-analyzer \
              @semantic-release/release-notes-generator \
              @semantic-release/git

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          npx semantic-release | tee semantic-release.log

