name: Release
on:
  release:
    types:
      - created

jobs:
  release:
    name: Build and Upload binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # get all tags to get latest version
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Build
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          go build -ldflags="-X github.com/spf13/tfenvgo/cmd.Version=$VERSION"

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          gh release upload $VERSION tfenvgo